version: '3.9'

x-healthcheck:
  &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 10

services:
  app:
    container_name: simple-crud
    image: simple-crud:0.0.1
    ports:
      - "8080:8080"
      - "8082:8081"
      - "5005:5005"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mockserver
      - postgres
      - redis
    healthcheck:
      test: /usr/local/app-healthcheck.sh
      <<: *default-healthcheck

  mockserver:
    container_name: simple-crud-mockserver
    image: mockserver/mockserver
    restart: always
    platform: linux/amd64
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectations.json
      MOCKSERVER_PERSIST_EXPECTATIONS: "true"
      MOCKSERVER_PERSISTED_EXPECTATIONS_PATH: /config/expectations.json
    volumes:
      - ./src/main/resources/docker/mockserver/:/config/

  postgres:
    container_name: simple-crud-pg-db
    image: postgres:15.4
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ~/postgresql/data/:/var/lib/postgresql/data/
      - ./src/main/resources/docker/postgres/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: pg_isready -U pguser -d postgres
      <<: *default-healthcheck

  redis:
    container_name: simple-crud-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:7.2.3
    ports:
      - "6379:6379"
    volumes:
      - ./src/main/resources/docker/redis/:/usr/local/etc/redis/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      <<: *default-healthcheck
